// Post-build script: reads dist/index.html (produced as a single self-
// contained file by vite-plugin-singlefile) and emits wordpress-embed.html
// that can be pasted directly into an Elementor HTML widget.
//
// Output structure:
//   <div id="tool">
//     <div id="root"></div>
//     <style>...all bundled CSS...</style>
//     <script>...all bundled JS...</script>
//   </div>

import { readFile, writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, '..');
const distHtml = resolve(projectRoot, 'dist/index.html');
const outFile = resolve(projectRoot, 'dist/wordpress-embed.html');

function extractAll(html, openTag, closeTag) {
  const out = [];
  let cursor = 0;
  while (true) {
    const start = html.indexOf(openTag, cursor);
    if (start === -1) break;
    const tagEnd = html.indexOf('>', start);
    if (tagEnd === -1) break;
    const close = html.indexOf(closeTag, tagEnd);
    if (close === -1) break;
    out.push(html.slice(start, close + closeTag.length));
    cursor = close + closeTag.length;
  }
  return out;
}

const html = await readFile(distHtml, 'utf8');

const styles = extractAll(html, '<style', '</style>').join('\n');
const scripts = extractAll(html, '<script', '</script>').join('\n');

const embed = `<!-- Taper Empire AI tool — single-file embed for Elementor HTML widget -->
<!-- Generated by scripts/extract-embed.mjs from dist/index.html -->
<div id="tool" style="scroll-margin-top:80px">
  <div id="root"></div>
  ${styles}
  ${scripts}
</div>
`;

await writeFile(outFile, embed, 'utf8');

console.log(`✓ wrote ${outFile}`);
console.log(`  styles: ${styles.length} chars · scripts: ${scripts.length} chars`);
