'use client'

import Image from 'next/image'
import Link from 'next/link'
import { motion } from 'framer-motion'
import { Button } from '@/components/ui/button'
import { easeLux } from '@/lib/motion'

/**
 * Phase X.3 — Real Results / See the transformation.
 *
 * Full-width edge-to-edge section with two opposing infinite marquees:
 *
 *   Row 1 (top)    — five "Before" portraits, scrolling LEFT
 *   Row 2 (bottom) — five "After"  portraits, scrolling RIGHT
 *
 * Each card carries a Before/After pill so the row reads instantly as
 * a transformation showcase. The marquees pause on hover and respect
 * prefers-reduced-motion via the global motion-reduce variant.
 *
 * Indices pair across rows — before-1 + after-1 are the same subject —
 * so visitors see the transformation by comparing column to column even
 * though the rows scroll in opposite directions.
 */

const PAIRS = [1, 2, 3, 4, 5] as const

const BEFORE_CARDS = PAIRS.map((n) => ({
  src:  `/real-results/before-${n}.webp`,
  blur: `/real-results/before-${n}-blur.webp`,
  alt:  `Subject ${n} — before TaperMatch reference`,
}))

const AFTER_CARDS = PAIRS.map((n) => ({
  src:  `/real-results/after-${n}.webp`,
  blur: `/real-results/after-${n}-blur.webp`,
  alt:  `Subject ${n} — after TaperMatch recommendation`,
}))

export function RealResults() {
  return (
    <section
      id="real-results"
      className="relative bg-ink text-soft border-t border-line grain-soft overflow-hidden"
    >
      {/* ── Centered editorial header ─────────────────────────────── */}
      <div className="max-w-3xl mx-auto px-6 lg:px-10 text-center pt-24 lg:pt-32">
        <motion.p
          initial={{ opacity: 0, y: 14 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-100px' }}
          transition={{ duration: 0.8, ease: easeLux }}
          className="type-eyebrow text-gold mb-6 inline-flex items-center gap-3"
        >
          <span aria-hidden="true" className="block h-px w-10 bg-gold/70" />
          Real Results
          <span aria-hidden="true" className="block h-px w-10 bg-gold/70" />
        </motion.p>

        <motion.h2
          initial={{ opacity: 0, y: 18 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-100px' }}
          transition={{ duration: 0.9, delay: 0.05, ease: easeLux }}
          className="font-display font-extrabold tracking-[-0.04em] text-[clamp(40px,6vw,80px)] leading-[0.98] mb-7"
        >
          See the
          <br />
          <span className="italic font-medium text-mute">transformation.</span>
        </motion.h2>

        <motion.p
          initial={{ opacity: 0, y: 12 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-100px' }}
          transition={{ duration: 0.8, delay: 0.1, ease: easeLux }}
          className="text-soft/65 text-base lg:text-lg leading-[1.7] max-w-xl mx-auto"
        >
          Real previews generated by our AI. Your results will look just as realistic —
          built against your face geometry, your texture, your maintenance reality.
        </motion.p>
      </div>

      {/* ── Marquee track 1 — Before, scrolling LEFT ──────────────── */}
      <div className="relative mt-16 lg:mt-20">
        <Marquee direction="left">
          {BEFORE_CARDS.map((c, i) => (
            <Card
              key={`b-${i}`}
              src={c.src}
              blur={c.blur}
              alt={c.alt}
              label="Before"
              labelTone="muted"
            />
          ))}
        </Marquee>
      </div>

      {/* ── Marquee track 2 — After, scrolling RIGHT ─────────────── */}
      <div className="relative mt-3 lg:mt-4">
        <Marquee direction="right">
          {AFTER_CARDS.map((c, i) => (
            <Card
              key={`a-${i}`}
              src={c.src}
              blur={c.blur}
              alt={c.alt}
              label="After"
              labelTone="gold"
            />
          ))}
        </Marquee>
      </div>

      {/* ── CTA strip ──────────────────────────────────────────────── */}
      <div className="max-w-3xl mx-auto px-6 lg:px-10 pt-16 lg:pt-20 pb-24 lg:pb-32 text-center">
        <motion.div
          initial={{ opacity: 0, y: 14 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-80px' }}
          transition={{ duration: 0.8, ease: easeLux }}
        >
          <Button asChild variant="cream" size="lg" shape="pill">
            <Link href="/tool">
              Get my own preview
              <span aria-hidden="true">→</span>
            </Link>
          </Button>
        </motion.div>
      </div>
    </section>
  )
}

/* ───────────────────────────────────────────────────────────────────────
 *  Marquee — duplicates children twice so the seam is invisible and the
 *  scroll loops cleanly. Direction-aware. Pauses on hover for inspection.
 * ─────────────────────────────────────────────────────────────────────── */
function Marquee({
  children,
  direction,
}: {
  children: React.ReactNode
  direction: 'left' | 'right'
}) {
  const animClass =
    direction === 'left'
      ? 'animate-marquee-left'
      : 'animate-marquee-right'

  return (
    <div className="group/marquee relative w-full overflow-hidden">
      <div
        className={`flex w-max items-center gap-3 lg:gap-4 ${animClass} motion-reduce:animate-none group-hover/marquee:[animation-play-state:paused]`}
        // Slow enough to feel cinematic, fast enough to be lively.
        style={{ animationDuration: '60s' }}
      >
        {/* First copy */}
        <div className="flex items-center gap-3 lg:gap-4 shrink-0 pl-3 lg:pl-4">{children}</div>
        {/* Second copy — keeps the loop seamless */}
        <div className="flex items-center gap-3 lg:gap-4 shrink-0" aria-hidden="true">{children}</div>
        {/* Third copy — extra buffer so wide displays never see the seam */}
        <div className="flex items-center gap-3 lg:gap-4 shrink-0" aria-hidden="true">{children}</div>
      </div>
    </div>
  )
}

/* ───────────────────────────────────────────────────────────────────────
 *  Card — portrait reference with bottom-left Before/After pill.
 * ─────────────────────────────────────────────────────────────────────── */
function Card({
  src,
  blur,
  alt,
  label,
  labelTone,
}: {
  src: string
  blur: string
  alt: string
  label: string
  labelTone: 'gold' | 'muted'
}) {
  return (
    <figure className="relative shrink-0 w-[200px] sm:w-[240px] lg:w-[280px] aspect-[4/5] overflow-hidden rounded-2xl border border-line bg-surface2">
      <Image
        src={src}
        alt={alt}
        fill
        quality={90}
        sizes="(max-width: 640px) 200px, (max-width: 1024px) 240px, 280px"
        placeholder="blur"
        blurDataURL={blur}
        className="object-cover object-center"
      />
      <figcaption className="absolute left-3 bottom-3">
        <span
          className={`inline-flex items-center text-[9px] font-semibold tracking-[0.32em] uppercase px-2.5 py-1 rounded-full backdrop-blur-md ${
            labelTone === 'gold'
              ? 'bg-gold/85 text-ink'
              : 'bg-ink/70 text-soft border border-soft/15'
          }`}
        >
          {label}
        </span>
      </figcaption>
    </figure>
  )
}
