'use client'

import Image from 'next/image'
import Link from 'next/link'
import { motion } from 'framer-motion'
import { Cinematic, SectionEyebrow } from '@/components/shared'
import { Button } from '@/components/ui/button'
import { easeLux } from '@/lib/motion'

/**
 * Phase 12 — Real Results / See the Transformation.
 *
 * A compact gallery wall using the editorial portrait library to show the
 * variety the recommendation engine produces. Every card has a 'Before'
 * tag in the reference; here we use a "Match preview" eyebrow on each so
 * the gallery reads as the engine's output sample, not a personal
 * portfolio. The hairline gold rule under the headline picks up the brand
 * gradient direction.
 */

const ROW_A = [
  { src: '/face-geometry/round.webp',   alt: 'Round face match preview',   eyebrow: 'Round · Low taper' },
  { src: '/face-geometry/oval.webp',    alt: 'Oval face match preview',    eyebrow: 'Oval · Low taper' },
  { src: '/face-geometry/square.webp',  alt: 'Square face match preview',  eyebrow: 'Square · Low taper' },
  { src: '/face-geometry/diamond.webp', alt: 'Diamond face match preview', eyebrow: 'Diamond · Mid taper' },
  { src: '/face-geometry/heart.webp',   alt: 'Heart face match preview',   eyebrow: 'Heart · Mid taper' },
] as const

const ROW_B = [
  { src: '/textures/straight.webp', alt: 'Straight hair match preview', eyebrow: 'Straight · Low–mid' },
  { src: '/textures/wavy.webp',     alt: 'Wavy hair match preview',     eyebrow: 'Wavy · Mid' },
  { src: '/textures/curly.webp',    alt: 'Curly hair match preview',    eyebrow: 'Curly · Low' },
  { src: '/textures/coily.webp',    alt: 'Coily hair match preview',    eyebrow: 'Coily · Temple / nape' },
  { src: '/hero/subject.webp',      alt: 'Editorial subject — TaperMatch preview', eyebrow: 'Sample · 94 / 100' },
] as const

export function RealResults() {
  return (
    <section
      id="real-results"
      className="relative bg-ink text-soft border-t border-line grain-soft overflow-hidden"
    >
      {/* Subtle brand-gradient wash up from the bottom */}
      <div
        aria-hidden="true"
        className="absolute inset-x-0 bottom-0 h-1/2 pointer-events-none"
        style={{
          background:
            'radial-gradient(ellipse 65% 70% at 50% 100%, rgba(143,122,88,0.10) 0%, transparent 70%)',
        }}
      />

      <Cinematic className="section-y relative">

        {/* ── Header ─────────────────────────────────────────────── */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-100px' }}
          transition={{ duration: 0.9, ease: easeLux }}
          className="text-center mb-14 lg:mb-20 max-w-3xl mx-auto"
        >
          <SectionEyebrow className="mb-6 justify-center inline-flex">
            Real Results
          </SectionEyebrow>
          <h2 className="font-display font-extrabold tracking-[-0.04em] text-[clamp(40px,6vw,84px)] leading-[1] mb-7">
            See the
            <br />
            <span className="italic font-medium text-mute">transformation.</span>
          </h2>
          <p className="text-soft/65 leading-[1.75] text-base lg:text-lg max-w-xl mx-auto mb-8">
            Real previews generated by our AI. Your results will look just as realistic — built
            against your face geometry, your texture, your maintenance reality.
          </p>
          <div
            aria-hidden="true"
            className="mx-auto h-px w-28 bg-gradient-to-r from-transparent via-gold/80 to-transparent"
          />
        </motion.div>

        {/* ── Two-row portrait gallery ───────────────────────────── */}
        <div className="space-y-4 lg:space-y-5">
          <GalleryRow items={ROW_A} startDelay={0} />
          <GalleryRow items={ROW_B} startDelay={0.12} />
        </div>

        {/* ── Inline CTA strip ──────────────────────────────────── */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-80px' }}
          transition={{ duration: 0.9, ease: easeLux }}
          className="mt-16 lg:mt-20 flex flex-col sm:flex-row items-center justify-between gap-6 px-6 lg:px-10 py-7 lg:py-8 rounded-hero border border-line bg-surface/30"
        >
          <div className="text-center sm:text-left">
            <p className="type-eyebrow text-gold mb-2">Run yours</p>
            <p className="font-display font-extrabold tracking-[-0.025em] text-soft text-xl lg:text-2xl leading-[1.2]">
              Sixty seconds. Three previews. <span className="italic font-medium text-mute">One brief.</span>
            </p>
          </div>
          <Button asChild variant="gold" size="lg" shape="pill">
            <Link href="/tool">
              See my transformation
              <span aria-hidden="true">→</span>
            </Link>
          </Button>
        </motion.div>
      </Cinematic>
    </section>
  )
}

interface GalleryItem { src: string; alt: string; eyebrow: string }

function GalleryRow({
  items, startDelay,
}: { items: readonly GalleryItem[]; startDelay: number }) {
  return (
    <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-3 lg:gap-4">
      {items.map((item, i) => (
        <motion.figure
          key={item.src + i}
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-60px' }}
          transition={{ duration: 0.7, delay: startDelay + i * 0.06, ease: easeLux }}
          className="group/preview relative aspect-[4/5] rounded-lg-x overflow-hidden border border-line bg-surface2"
        >
          <Image
            src={item.src}
            alt={item.alt}
            fill
            quality={88}
            sizes="(max-width: 640px) 50vw, (max-width: 768px) 33vw, 20vw"
            className="object-cover object-center transition-transform duration-700 ease-lux group-hover/preview:scale-[1.04]"
          />
          <div
            aria-hidden="true"
            className="absolute inset-0 pointer-events-none"
            style={{ background: 'linear-gradient(180deg, transparent 55%, rgba(7,7,7,0.85) 100%)' }}
          />
          <figcaption className="absolute inset-x-0 bottom-0 px-3 pb-3">
            <span className="inline-flex items-center gap-1.5 text-[9px] font-semibold tracking-[0.28em] uppercase text-gold border border-gold/40 bg-ink/55 backdrop-blur-sm px-2.5 py-1 rounded-pill">
              <span aria-hidden="true" className="w-1.5 h-1.5 rounded-full bg-gold animate-pulse" />
              Preview
            </span>
            <p className="mt-2 text-[10px] font-medium tracking-[0.28em] uppercase text-soft/85 truncate">
              {item.eyebrow}
            </p>
          </figcaption>
        </motion.figure>
      ))}
    </div>
  )
}
